### ISSUE TITLE
Add sanity checks for variables?

### ISSUE THREAD

**Issue by orichters** [IAMconsortium/common-definitions#51]
Dear @danielhuppmann,

I wonder whether it is planned or advisable to add some "sanity checks" for variables:
```
- Consumption:
    description: total consumption of all goods, by all consumers in a region
    unit: billion US$2010/yr
    min: 0
- Consumption Share|Food:
    description: share of consumption allocated to food
    unit: %
    min: 0
    max: 100
```
There were such attempts in [CDLINKS](https://github.com/IAMconsortium/iamc/blob/master/inst/extdata/CDLINKS.csv) and I think that would be really useful (and could in the future also be checked in the submission process):
