### ISSUE TITLE
Variables reporting Shares  / Rates

### ISSUE THREAD

**Issue by FlorianLeblancDr** [IAMconsortium/common-definitions#60]
Thanks @FlorianLeblancDr for the response.

1. Yes, we should definitely review whether these identifiers are relevant and we should remove them where possible.
2. About the shares: In this issue, I'm more concerned about the naming convention rather than where/how it is computed. From the perspective of a user of the Scenario Explorer, they will find both "Unemployment" (in millions) and "Unemployment (Rate)" (in %) useful, so we should provide both.

_Originally posted by @danielhuppmann in https://github.com/IAMconsortium/common-definitions/issues/55#issuecomment-1944019955_

**Comment by FlorianLeblancDr** [comment]
Raising a new issue on variable defined as Shares / Rates, following this discussion.

I wondered if having "Shares" variables is not misleading, as it let each modelling team decide what is the denominator.
and if it won't be equivalent to request the variable you want to compute shares inside the database.

For example, instead of requesting employment as a share of something (something being specified in the definition), one could only request (for example) total active population and let the share be computed elsewhere?

Example:

```
- Unemployment:
    definition: Number of unemployed inhabitants (based on ILO classification)
    unit: million
- Unemployment|Rate:
    definition: Fraction of unemployed inhabitants (based on ILO classification)
    unit: '%'
```

To be replaced by:

```
- Unemployment:
    definition: Number of unemployed inhabitants (based on ILO classification)
    unit: million
```

Daniel raised a good point: "From the perspective of a user of the Scenario Explorer, they will find both "Unemployment" (in millions) and "Unemployment (Rate)" (in %) useful, so we should provide both".

So my final suggestion would be to remain exhaustive, and provide explicitly in the definition the corresponding numerator and denominator, and add new variables defining denominators each time a "Rate" / "Share" variable is defined. This would give for the example:

```
- Unemployment:
    definition: Number of unemployed inhabitants (based on ILO classification)
    unit: million
- Population|Active:
    definition: Active population.
    unit: '%'
- Unemployment|Rate:
    definition: Fraction of unemployed inhabitants ('Unemployment') over active population ('Population|Active'
    unit: '%')
```
