### ISSUE TITLE
Variables for production of cement and steel

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/common-definitions#72]
The @IAMconsortium/common-definitions-sdg-indicators group in #53  suggested to add the following variables that are directly related to the domain of the @IAMconsortium/common-definitions-macro-economy group.

```yaml
- Production|Cement:
    definition: production of cement
    sdg: 9
    unit: Mt/year
- Production|Steel:
    definition: production of steel
    sdg: 9
    unit: Mt/year
- Production|Steel|Primary:
    definition: production of primary steel
    sdg: 9
    unit: Mt/year
- Production|Steel|Secondary:
    definition: production of secondary steel
    sdg: 9
    unit: Mt/year
- Value Added|Industry|Other Industry:
    definition:
    sdg: 9
    unit: billion US$2010
```
